names<-c("Date","Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_intensity", "Sub_metering_1", "Sub_metering_2","Sub_metering_3")
data=read.table("household_power_consumption.txt",col.names=names,sep=";",na.strings="?",skip=66637, nrows=2880)
data$Date<-as.Date(data$Date, format="%d/%m/%Y")
dateFull <- paste(data$Date, data$Time)
data$DateFull <- as.POSIXct(dateFull)
plot(data$Global_active_power~data$DateFull, type="l", ylab="Global Active Power (kilowatts)", xlab="")
dev.copy(png, "plot2.png")
dev.off()